Add classloader inheritance provider
Allows inheritance to be loaded through URLClassLoader, as an alternative
to JarFile/Jar with JarInheritanceProvider. This is how CB loads plugins, and
it may avoid some of the idiosyncrasies in loading the jar directly as a zip -
for example https://github.com/MinecraftPortCentral/MCPC-Plus/issues/51
java.util.zip.ZipException: duplicate entry (CB can load this plugin just fine)

Also allows more convenient remapping in PluginClassLoader, since the
URLClassLoader object is readily available